title: Lookup Values
description: Extract values to use for the demo/FeatureRichExample.
sourceEndpoints:
  MySQL:
    type: SQL
    urlTemplate: "mysql://localhost:2001/test"
    username: user
    password: T0p-Secret
source:
  type: SQL
  endpoint: MySQL
  replaceDoubleQuotes: true
  query: |
    select
        value as label
        , value
    from
        "RefData"
    where
        "refId" in (select "refId" from "ManyData")
    order by
       "ordering"
formats:
- type: JSON
- type: HTML
  name: table
