title: Lookup Values
description: Extract values to use for the demo/FeatureRichExample.
sourceEndpoints:
  MySQL:
    type: SQL
    urlTemplate: "mysql://localhost:2001/test"
    username: user
    password: T0p-Secret
source:
  type: SQL
  endpoint: MySQL
  replaceDoubleQuotes: true
  query: |
    select distinct 
      value 
    from 
      "ManyData" m 
      join "RefData" r on r."refId" = m."refId"
    order by
      "ordering"
formats:
- type: JSON
