version: "3.8"

services:
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
    - 2001:3306
    environment:
      MYSQL_ROOT_PASSWORD: T0p-secret
      MYSQL_USER: user
      MYSQL_PASSWORD: T0p-secret
      MYSQL_DATABASE: test
  
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
    - 2002:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: T0p-secret

  postgresql:
    image: postgres:14.1-alpine
    ports:
    - 2003:5432
    command: postgres -c log_min_duration_statement=0
    environment:
      POSTGRES_PASSWORD: T0p-secret
      POSTGRES_USER: postgres
      POSTGRES_DB: test
      
  query-engine:
    image: ghcr.io/yaytay/query-engine-design-mode-0-0:0.0.8
    ports:
    - 2000:8080
    environment:
    - query-engine.httpServerOptions.port=8080
    - query-engine.logging.level.uk=TRACE
    - query-engine.audit.dataSource.url=jdbc:mysql://mysql/test?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    - query-engine.audit.dataSource.user.username=user
    - query-engine.audit.dataSource.user.password=T0p-secret
    - query-engine.audit.dataSource.adminUser.username=user
    - query-engine.audit.dataSource.adminUser.password=T0p-secret
    - query-engine.audit.retryLimit=100
    - query-engine.audit.retryIncrementMs=500
    - query-engine.jwt.acceptableIssuerRegexes[0]=.*
