= JwtValidationConfig



[cols="1,1a,4a",stripes=even]
|===
| Name
| Type
| Details


| issuer
| link:https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/String.html[String]
| Set the fixed issuer to be used for all requests.

This is useful when all tokens that will be encountered have the same issuer,
 which could either be because the Query Engine is not being used in a SAAS deployment or because a single
 token service is used for all clients.
 

If a fixed issuer is not configured the Host on the request will be used as the issuer.
 

Setting this value does not remove the need to configure the acceptable issuers (but probably means that a
 regular expression with no variation should be used).
| issuerHostPath
| link:https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/String.html[String]
| Set the path to be appended to the Host to derive the issuer.

Usually an issuer has an empty path, being just https://host[:port]/ however it is perfectly valid for an issuer
 to have a path as long as, when ".well-known/openid-configuration" is appended to it it results in a valid URL
 to the OpenID configuration for that issuer.
 

This value is <em>not</em>  used to signify that the issuer should be derived from the header, that indication is driven entirely 
 by the fixed  value.
| requiredAudience
| link:https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/String.html[String]
| Set the audience value that must be included in any token for the query engine to accept it.


| acceptableIssuersFile
| link:https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/String.html[String]
| Set the path to the acceptable issuers file.

This is a core security control and must be set as tightly as possible.
 

The file itself may be updated in a running system, but the path to the file is immutable.
 

An issuer is considered acceptable if it matches an entry in this file OR an acceptableIssuerRegex.
| filePollPeriodDuration
| link:https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/time/Duration.html[Duration]
| Get the time between checks of the file (also the time that the file must stabilise before it is re-read).

Thus the delay between a change to the file being made and being picked up will be 
 between filePollPeriodMs and 2 * filePollPeriodMs.
 

Checks of the file are based entirely on the last-modified timestamp - if the file is on a filesystem that
 does not support the last-modified timestamp changes will never be picked up.
| acceptableIssuerRegexes
| link:https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/util/List.html[List]<link:https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/String.html[String]>
| Set the list of regular expressions that are used to define acceptable token issuers.

This is a core security control and must be set as tightly as possible.
 

An issuer is considered acceptable if it matches one of these regular expressions, OR it matches an entry in the acceptableIssuersFile.
| defaultJwksCacheDuration
| link:https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/time/Duration.html[Duration]
| Set the default period to cache JWKS data for.

This is expected to be overridden by cache-control/max-age headers on the JWKS response, so the default value is usually reasonable.
| jwksEndpoints
| link:https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/util/List.html[List]<link:https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/String.html[String]>
| Get the explicitly configured endpoints that will be used to download JWK sets.

If any values are set here they will be the only endpoints used for downloading JSON Web Keys.
 If this value is empty the issuer will be determined (typically from the Host header, see  and ), tested for acceptability, and used to perform OpenID Discovery.
 

In a SAAS deployment the appropriate setting depends on whether the clients share a single JWKS.
 If the JWKS is shared the URL for it should be provided here, if there is a separate pool of keys for each client then this setting should be left empty and OpenID Discovery will be used for each issuer.
 

Regardless of how the JWKS endpoints are found, the acceptable issuers must be configured as tightly as possible.
|===
