= JwtValidationConfig



[cols="1,1a,4a",stripes=even]
|===
| Name
| Type
| Details


| requiredAudience
| link:https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/String.html[String]
| Set the audience value that must be included in any token for the query engine to accept it.


| acceptableIssuersFile
| link:https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/String.html[String]
| Set the path to the acceptable issuers file.

This is a core security control and must be set as tightly as possible.
 

The file itself may be updated in a running system, but the path to the file is immutable.
 

An issuer is considered acceptable if it matches an entry in this file OR an acceptableIssuerRegex.
| filePollPeriodDuration
| link:https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/time/Duration.html[Duration]
| Get the time between checks of the file (also the time that the file must stabilise before it is re-read).

Thus the delay between a change to the file being made and being picked up will be 
 between filePollPeriodMs and 2 * filePollPeriodMs.
 

Checks of the file are based entirely on the last-modified timestamp - if the file is on a filesystem that
 does not support the last-modified timestamp changes will never be picked up.
| acceptableIssuerRegexes
| link:https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/util/List.html[List]<link:https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/lang/String.html[String]>
| Set the list of regular expressions that are used to define acceptable token issuers.

This is a core security control and must be set as tightly as possible.
 

An issuer is considered acceptable if it matches one of these regular expressions, OR it matches an entry in the acceptableIssuersFile.
| defaultJwksCacheDuration
| link:https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/time/Duration.html[Duration]
| Set the default period to cache JWKS data for.

This is expected to be overridden by cache-control/max-age headers on the JWKS response, so the default value is usually reasonable.
|===
