= Condition

Conditions are expressions using link:https://commons.apache.org/proper/commons-jexl/[JEXL]  that control access to something.

Conditions are a single expression.
 
 

Conditions can be applied to:
 
 * entire directories (in the permissions.jexl file)
 * Pipelines
 * Endpoints
 


The context of a Condition includes a variable called "req" that includes:
 
 * requestId
 A unique ID for the request.  If Distributed Tracing is enabled this will be the Span ID, otherwise it will be a random UUID.
 * String url
 The full URL of the request.
 * host
 The host extracted from the URL.
 * arguments
 

A link:https://vertx.io/docs/apidocs/io/vertx/core/MultiMap.html[io.vertx.core.MultiMap]  of query string arguments.
 * headers
 

A link:https://vertx.io/docs/apidocs/io/vertx/core/MultiMap.html[io.vertx.core.MultiMap]  of request headers.
 * cookies
 

A link:https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Map.html[java.util.Map]  map of request cookies.
 * clientIp
 

The IP address of client making the request, taken from the first of:
 
 * The X-Cluster-Client-IP header.
 * The X-Forwarded-For header.
 * The actual IP address making the TCP connection.
 
* jwt
 The link:https://jwt.io/[Json Web Token]  associated with the request, if any.
 * clientIpIsIn
 A function that receives an array of IP addresses or subnets (in slash notation) and returns true if the clientIp matches any of them.
 


A condition should return either the true or false.
 In addition if it returns the string "true" it will be considered to be true.
 Any other return value will be considered false.
 

Some examples Conditions are
 
 * 
[source]
----
requestContext != null
----
Checks that the request context is not null, pretty useless in a live environment.
 * 
[source]
----
requestContext.clientIpIsIn('127.0.0.1/32','172.17.0.1/16','0:0:0:0:0:0:0:1')
----
Checks that the client IP address is either localhost or in "172.17.0.0/16".
 * 
[source]
----
requestContext.host == 'localhost'
----
Checks that the host on the request is localhost.
 
When referencing optional arguments use "Map accesses" (`+args['argName']+`) rather than "JavaBean property access" (`+args.argName+`).
 The dotted approach will generate an error if the argument is not supplied.
 



[cols="1,1a,4a",stripes=even]
|===
| Name
| Type
| Details


| [[logger]]logger
| link:https://www.slf4j.org/api/org/slf4j/Logger.html[Logger]
| 

| [[expression]]expression
| link:https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/String.html[String]
| 

|===
