version: "3.8"

services:
  mysql:
    image: mysql:8.3
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-log-bin
    ports:
    - 2001:3306
    environment:
      MYSQL_ROOT_PASSWORD: T0p-Secret
      MYSQL_USER: user
      MYSQL_PASSWORD: T0p-Secret
      MYSQL_DATABASE: test
  
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
    - 2002:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: T0p-Secret

  postgresql:
    image: postgres:16.2-alpine
    ports:
    - 2003:5432
    command: postgres -c log_min_duration_statement=0
    environment:
      POSTGRES_PASSWORD: T0p-Secret
      POSTGRES_USER: postgres
      POSTGRES_DB: test
  
  jaeger:
    image: jaegertracing/all-in-one:1.56
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
    - 5775:5775/udp
    - 6831:6831/udp
    - 6832:6832/udp
    - 5778:5778
    - 4317:4317
    - 4318:4318
    - 16686:16686
    - 14268:14268
      
  query-engine:
    image: ghcr.io/yaytay/query-engine-design-mode:0.0.33-48-main
    ports:
    - 2000:8080
    volumes:
    - ./pipelines:/var/query-engine
    environment:
    - query-engine.httpServerOptions.port=8080
    - query-engine.logging.level.uk=DEBUG
    - query-engine.persistence.dataSource.url=jdbc:mysql://mysql/test?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    - query-engine.persistence.dataSource.user.username=user
    - query-engine.persistence.dataSource.user.password=T0p-Secret
    - query-engine.persistence.dataSource.adminUser.username=user
    - query-engine.persistence.dataSource.adminUser.password=T0p-Secret
    - query-engine.persistence.retryLimit=100
    - query-engine.persistence.retryIncrementMs=500
    - query-engine.jwt.acceptableIssuerRegexes[0]=.*
    - query-engine.tracing.serviceName=query-engine2
    - query-engine.tracing.protocol=otlphttp    
    - query-engine.tracing.url=http://jaeger:4318/v1/traces
    - query-engine.sampleDataLoads[0].url=mysql://query-engine-mysql-1:3306/test
    - query-engine.sampleDataLoads[0].adminUser.username=user
    - query-engine.sampleDataLoads[0].adminUser.password=T0p-Secret
    - query-engine.sampleDataLoads[1].url=postgresql://query-engine-postgresql-1:5432/test
    - query-engine.sampleDataLoads[1].adminUser.username=postgres
    - query-engine.sampleDataLoads[1].adminUser.password=T0p-Secret
    - query-engine.sampleDataLoads[2].url=sqlserver://query-engine-mssql-1:1433/test
    - query-engine.sampleDataLoads[2].adminUser.username=sa
    - query-engine.sampleDataLoads[2].adminUser.password=T0p-Secret
    - query-engine.baseConfigPath=/var/query-engine
    - query-engine.outputCacheDir=/var/cache/query-engine
    - query-engine.processors.tempDir=/tmp/query-engine
    
