/*
 * Copyright (C) 2023 jtalbut
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package uk.co.spudsoft.query.main;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.time.Duration;
import java.time.temporal.ChronoUnit;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;

/**
 * Configuration of the session/login subsystem.
 * <p>
 * Sessions are not required by the REST API, but can be used if set up.
 * A session is effectively just a cookie that links to a JWT generated by the login handler.
 * <p>
 * Session data can be stored either in memory or in a database, depending on whether or not {@link Parameters#persistence} is set.
 * 
 * @author jtalbut
 */
public class SessionConfig {
  
  private boolean requireSession;
  private Duration purgeDelay = Duration.of(1, ChronoUnit.HOURS);
  private int stateLength = 120;
  private int codeVerifierLength = 120;
  private int nonceLength = 120;
  private CookieConfig sessionCookie = new CookieConfig("qe-session");
  
  private Map<String, AuthEndpoint> oauth = new HashMap<>();

  /**
   * Get the flag to indicate that a session is required for all REST API calls.
   * @return the flag to indicate that a session is required for all REST API calls.
   */
  public boolean isRequireSession() {
    return requireSession;
  }

  /**
   * Set the flag to indicate that a session is required for all REST API calls.
   * @param requireSession the flag to indicate that a session is required for all REST API calls.
   */
  public void setRequireSession(boolean requireSession) {
    this.requireSession = requireSession;
  }

  /**
   * The purging period for the session data.
   * <p>
   * A scheduled task is set up to run this often that will remove any expired sessions from both the in-memory cache and the database.
   * @return purging period for the session data.
   */
  public Duration getPurgeDelay() {
    return purgeDelay;
  }

  /**
   * The purging period for the session data.
   * <p>
   * A scheduled task is set up to run this often that will remove any expired sessions from both the in-memory cache and the database.
   * @param purgeDelay purging period for the session data.
   */
  public void setPurgeDelay(Duration purgeDelay) {
    this.purgeDelay = purgeDelay;
  }

  /**
   * Length of the state passed in to the OAuth authentication endpoint.
   * @return length of the state passed in to the OAuth authentication endpoint.
   */
  public int getStateLength() {
    return stateLength;
  }

  /**
   * Length of the state passed in to the OAuth authentication endpoint.
   * @param stateLength length of the state passed in to the OAuth authentication endpoint.
   */
  public void setStateLength(int stateLength) {
    this.stateLength = stateLength;
  }

  /**
   * Length of the PKCE code verifier passed in to the OAuth authentication endpoint.
   * @return length of the PKCE code verifier passed in to the OAuth authentication endpoint.
   */
  public int getCodeVerifierLength() {
    return codeVerifierLength;
  }

  /**
   * Length of the PKCE code verifier passed in to the OAuth authentication endpoint.
   * @param codeVerifierLength length of the PKCE code verifier passed in to the OAuth authentication endpoint.
   */
  public void setCodeVerifierLength(int codeVerifierLength) {
    this.codeVerifierLength = codeVerifierLength;
  }

  /**
   * Length of the nonce passed in to the OAuth authentication endpoint.
   * @return length of the nonce passed in to the OAuth authentication endpoint.
   */
  public int getNonceLength() {
    return nonceLength;
  }

  /**
   * Length of the nonce passed in to the OAuth authentication endpoint.
   * @param nonceLength length of the nonce passed in to the OAuth authentication endpoint.
   */
  public void setNonceLength(int nonceLength) {
    this.nonceLength = nonceLength;
  }
  
  /**
   * Map of OAuth endpoints that the user can choose from when logging in.
   * @return map of OAuth endpoints that the user can choose from when logging in.
   */
  @SuppressFBWarnings(value = "EI_EXPOSE_REP", justification = "Configuration parameter, should not be changed after being initialized by Jackson")
  public Map<String, AuthEndpoint> getOauth() {
    return oauth;
  }

  /**
   * Map of OAuth endpoints that the user can choose from when logging in.
   * @param oauth map of OAuth endpoints that the user can choose from when logging in.
   */
  @SuppressFBWarnings(value = "EI_EXPOSE_REP2", justification = "Configuration parameter, should not be changed after being initialized by Jackson")
  public void setOauth(Map<String, AuthEndpoint> oauth) {
    this.oauth = oauth;
  }  

  /**
   * Configuration of the cookie used for the session.
   * @return configuration of the cookie used for the session.
   */
  @SuppressFBWarnings("EI_EXPOSE_REP")
  public CookieConfig getSessionCookie() {
    return sessionCookie;
  }

  /**
   * Configuration of the cookie used for the session.
   * @param sessionCookie configuration of the cookie used for the session.
   */
  @SuppressFBWarnings("EI_EXPOSE_REP2")
  public void setSessionCookie(CookieConfig sessionCookie) {
    this.sessionCookie = sessionCookie;
  }

  /**
   * Validate the session configuration.
   * @param path The configuration path to this object.
   * @throws IllegalArgumentException if something is invalid.
   */
  public void validate(String path) throws IllegalArgumentException {
    if (sessionCookie == null) {
      throw new IllegalArgumentException(path + ".sessionCookie not configured");
    }
    sessionCookie.validate(path +  ".sessionCookie");
    if (oauth != null) {
      for (Entry<String, AuthEndpoint> entry : oauth.entrySet()) {
        entry.getValue().validate(path + ".oauth." + entry.getKey());
      }
    }
    
  }
  
}
